from PyQt5 import uic
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 254)
        self.frame = QFrame(Dialog)
        self.frame.setGeometry(QRect(10, 10, 101, 111))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.frame.setObjectName("frame")
        self.wesolaRadio = QRadioButton(self.frame)
        self.wesolaRadio.setGeometry(QRect(10, 10, 82, 17))
        self.wesolaRadio.setObjectName("wesolaRadio")
        self.normalnaRadio = QRadioButton(self.frame)
        self.normalnaRadio.setGeometry(QRect(10, 40, 82, 17))
        self.normalnaRadio.setObjectName("normalnaRadio")
        self.smutnaRadio = QRadioButton(self.frame)
        self.smutnaRadio.setGeometry(QRect(10, 70, 82, 17))
        self.smutnaRadio.setObjectName("smutnaRadio")
        self.frame_2 = QFrame(Dialog)
        self.frame_2.setGeometry(QRect(10, 130, 101, 111))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.wesolaCheckbox = QCheckBox(self.frame_2)
        self.wesolaCheckbox.setGeometry(QRect(10, 10, 70, 17))
        self.wesolaCheckbox.setCheckable(False)
        self.wesolaCheckbox.setObjectName("wesolaCheckbox")
        self.smutnaCheckbox = QCheckBox(self.frame_2)
        self.smutnaCheckbox.setGeometry(QRect(10, 70, 70, 17))
        self.smutnaCheckbox.setCheckable(False)
        self.smutnaCheckbox.setObjectName("smutnaCheckbox")
        self.normalnaCheckbox = QCheckBox(self.frame_2)
        self.normalnaCheckbox.setGeometry(QRect(10, 40, 70, 17))
        self.normalnaCheckbox.setCheckable(False)
        self.normalnaCheckbox.setObjectName("normalnaCheckbox")
        self.okButton = QPushButton(Dialog)
        self.okButton.setGeometry(QRect(310, 20, 75, 23))
        self.okButton.setCheckable(False)
        self.okButton.setObjectName("okButton")
        self.cancelButton = QPushButton(Dialog)
        self.cancelButton.setGeometry(QRect(310, 50, 75, 23))
        self.cancelButton.setObjectName("cancelButton")
        self.progressBar = QProgressBar(Dialog)
        self.progressBar.setGeometry(QRect(120, 170, 31, 71))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setOrientation(Qt.Vertical)
        self.progressBar.setObjectName("progressBar")
        self.iconView = QGraphicsView(Dialog)
        self.iconView.setGeometry(QRect(130, 10, 141, 141))
        self.iconView.setObjectName("iconView")

        self.retranslateUi(Dialog)
        QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QApplication.translate("Dialog", "Dialog", None, -1))
        self.wesolaRadio.setText(QApplication.translate("Dialog", "wesola", None, -1))
        self.normalnaRadio.setText(QApplication.translate("Dialog", "normalna", None, -1))
        self.smutnaRadio.setText(QApplication.translate("Dialog", "smutna", None, -1))
        self.wesolaCheckbox.setText(QApplication.translate("Dialog", "wesola", None, -1))
        self.smutnaCheckbox.setText(QApplication.translate("Dialog", "smutna", None, -1))
        self.normalnaCheckbox.setText(QApplication.translate("Dialog", "normalna", None, -1))
        self.okButton.setText(QApplication.translate("Dialog", "Ok", None, -1))
        self.cancelButton.setText(QApplication.translate("Dialog", "Cancel", None, -1))

